=== adempiere/adempiere/utils_dev/trl/adempiereTrl.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--Adempiere(tm) Version 2.5.1a/2004-03-15 - Smart ERP & CRM - Copyright (c) 1999-2004 Jorg Janke -->
<!--Adempiere Translation file DTD -->
<!ELEMENT adempiereTrl (row+)>
<!ATTLIST adempiereTrl
	table CDATA #REQUIRED
	language CDATA #REQUIRED
>
<!ELEMENT row (value+)>
<!ATTLIST row
	trl CDATA #IMPLIED
	id CDATA #REQUIRED
>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value
	original CDATA #IMPLIED
	column CDATA #REQUIRED
>

=== adempiere/adempiere/data/th_TH/AD_Field_Trl_th_TH.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Adempiere(r) Release 2.5.2c_2005-05-05 - Smart ERP & CRM - (c) 1999-2005 Adempiere (r); Implementation: Thailand 25480520-1017 - Unsupported-->
<!--<!DOCTYPE adempiereTrl PUBLIC "-//ComPiere, Inc.//DTD Adempiere Translation 1.0//EN" "http://www.adempiere.net/dtd/adempiereTrl.dtd">-->
<adempiereTrl language="th_TH" table="AD_Field">
 <row id="1546" trl="Y">
  <value column="Name" original="Link Column">คอลัมน์เชื่อมโยง</value>
  <value column="Description" original="Link Column for Multi-Parent tables">คอลัมน์เชื่อมโยงสำหรับตาราง Multi-Parent</value>
  <value column="Help" original="The Link Column indicates which column is the primary key for those situations where there is more than one parent.  Only define it, if the table has more than one parent column (e.g. AD_User_Roles).">คอลัมน์เชื่อมโยง แสดงคอลัมน์ซึ่งเป็นค่าหลัก (primary key) ของตารางซึ่งมีมากกว่าหนึ่ง parent  เฉพาะที่ให้นิยามมันไว้เท่านั้น, ว่าตารางนั้นมีคอลัมน์ parent มากกว่าหนึ่งหรือไม่ (เช่น AD_User_Roles)</value>
 </row>
 <row id="2124" trl="Y">
  <value column="Name" original="Language">ภาษา</value>
  <value column="Description" original="Language for this Business Partner if Multi-Language enabled">ภาษาสำหรับบริษัทคู่ค้านี้ถ้าทำงาน หลายภาษา</value>
  <value column="Help" original="The Language identifies the language to use for display and formatting documents. It requires, that on Client level, Multi-Lingual documents are selected and that you have created/loaded the language.">The Language identifies the language to use for display and formatting documents. It requires, that on Client level, Multi-Lingual documents are selected and that you have created/loaded the language.</value>
 </row>
 <row id="3665" trl="Y">
  <value column="Name" original="Start Node">โหนดเริ่มต้น</value>
  <value column="Description" original="Workflow Node, step or process">Workflow Node, step or process</value>
  <value column="Help" original="The Workflow Node indicates a unique step or process in a Workflow.">The Workflow Node indicates a unique step or process in a Workflow.</value>
 </row>
 <row id="4055" trl="Y">
  <value column="Name" original="Tax Amount">Tax Amount</value>
  <value column="Description" original="Tax Amount for Credit Card transaction">Tax Amount for Credit Card transaction</value>
  <value column="Help" original="The Tax Amount displays the total tax amount. The tax amount is only used for credit card processing.">The Tax Amount displays the total tax amount. The tax amount is only used for credit card processing.</value>
 </row>
 <row id="4253" trl="Y">
  <value column="Name" original="Only Currency">เฉพาะสกุลเงิน</value>
  <value column="Description" original="Restrict accepting only this currency">Restrict accepting only this currency</value>
  <value column="Help" original="The Only Currency field indicates that this bank account accepts only the currency identified here.">The Only Currency field indicates that this bank account accepts only the currency identified here.</value>
 </row>
 <row id="4462" trl="Y">
  <value column="Name" original="Business Partner / Sales Rep">บริษัทคู่ค้า / พนักงานขาย</value>
  <value column="Description" original="Identifies a Business Partner (Sales Rep) receiving the Commission">เป็นการระบุบริษัทคู่ค้า(พนักงานขาย)ซึ่งรับค่านายหน้า</value>
  <value column="Help" original="The Business Partner should be a vendor and may be a Sales Representative">บริษัทคู่ค้า ควรจะเป็นผู้จำหน่ายสินค้าและอาจจะเป็นพนักงานขายด้วยก็ได้</value>
 </row>
 <row id="4725" trl="Y">
  <value column="Name" original="Acknowledge">รับทราบ</value>
  <value column="Description" original="System Notice acknowledged">รับทราบข้อสังเกตุจากระบบแล้ว</value>
  <value column="Help" original="The Acknowledged checkbox indicates if this notice does not need to be retained.">The Acknowledged checkbox indicates if this notice does not need to be retained.</value>
 </row>
 <row id="5092" trl="Y">
  <value column="Name" original="Driving Column">Driving Column</value>
  <value column="Description" original="Column which controls all tabs in the workbench">Column which controls all tabs in the workbench</value>
  <value column="Help" original=""/>
 </row>
 <row id="8985" trl="Y">
  <value column="Name" original="Document No">เลขที่เอกสาร</value>
  <value column="Description" original="Document sequence number of the document">Document sequence number of the document</value>
  <value column="Help" original="The document number is usually automatically generated by the system and determined by the document type of the document. If the document is not saved, the preliminary number is displayed in &quot;&lt;&gt;&quot;.&#10;&#10;If the document type of your document has no automatic document sequence defined, the field is empty if you create a new document. This is for documents which usually have an external number (like vendor invoice).  If you leave the field empty, the system will generate a document number for you. The document sequence used for this fallback number is defined in the &quot;Maintain Sequence&quot; window with the name &quot;DocumentNo_&lt;TableName&gt;&quot;, where TableName is the actual name of the table (e.g. C_Order).">The document number is usually automatically generated by the system and determined by the document type of the document. If the document is not saved, the preliminary number is displayed in "&lt;&gt;".

If the document type of your document has no automatic document sequence defined, the field is empty if you create a new document. This is for documents which usually have an external number (like vendor invoice).  If you leave the field empty, the system will generate a document number for you. The document sequence used for this fallback number is defined in the "Maintain Sequence" window with the name "DocumentNo_&lt;TableName&gt;", where TableName is the actual name of the table (e.g. C_Order).</value>
 </row>
 <row id="10097" trl="Y">
  <value column="Name" original="Value">ค่า</value>
  <value column="Description" original="Condition Value">ค่าเงื่อนไข</value>
  <value column="Help" original=""/>
 </row>
 <row id="10886" trl="Y">
  <value column="Name" original="Overwrite Project">Overwrite Project</value>
  <value column="Description" original="Overwrite the account segment Project with the value specified">Overwrite the account segment Project with the value specified</value>
  <value column="Help" original="If not overwritten, the value of the original account combination is used. If selected, but not specified, the segment is set to null.">If not overwritten, the value of the original account combination is used. If selected, but not specified, the segment is set to null.</value>
 </row>
</adempiereTrl>

=== adempiere/adempiere/data/bg_BG/CM_CStage_Trl_bg_BG.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--<!DOCTYPE adempiereTrl PUBLIC "-//ComPiere, Inc.//DTD Adempiere Translation 1.0//EN" "http://www.adempiere.net/dtd/adempiereTrl.dtd">-->
<adempiereTrl language="bg_BG" table="CM_CStage">
 <row id="100" trl="Y">
  <value column="Meta_Description" original=""/>
  <value column="Meta_Keywords" original=""/>
  <value column="Name" original="Products">Продукти</value>
  <value column="ContainerXML" original=""/>
  <value column="StructureXML" original=""/>
  <value column="Title" original=""/>
 </row>
 <row id="101" trl="Y">
  <value column="Meta_Description" original="This is the homesite of GardenWorld, it would be a good idea to place some real content in here">This is the homesite of GardenWorld, it would be a good idea to place some real content in here</value>
  <value column="Meta_Keywords" original="GardenWorld, Adempiere">GardenWorld, Adempiere</value>
  <value column="Name" original="Home of Gardenworld">Домът на "Градински Свят"</value>
  <value column="ContainerXML" original=""/>
  <value column="StructureXML" original=""/>
  <value column="Title" original="Home of Gardenworld">Домът на "Градински Свят"</value>
 </row>
 <row id="102" trl="Y">
  <value column="Meta_Description" original="Our plum trees are the best in the world">Our plum trees are the best in the world</value>
  <value column="Meta_Keywords" original="plum tree gardenworld">plum tree gardenworld</value>
  <value column="Name" original="Plum Tree">Ñëèâà</value>
  <value column="ContainerXML" original=""/>
  <value column="StructureXML" original=""/>
  <value column="Title" original="Powerfull Plum Tree">Powerfull Plum Tree</value>
 </row>
 <row id="103" trl="Y">
  <value column="Meta_Description" original="This is  short summary of the advantages of our wonderfull oak tree">This is  short summary of the advantages of our wonderfull oak tree</value>
  <value column="Meta_Keywords" original="oak tree gardenworld">oak tree gardenworld</value>
  <value column="Name" original="Oak Tree">Äúá</value>
  <value column="ContainerXML" original=""/>
  <value column="StructureXML" original=""/>
  <value column="Title" original=""/>
 </row>
 <row id="104" trl="Y">
  <value column="Meta_Description" original="Error 404">Error 404</value>
  <value column="Meta_Keywords" original="Gardenadmin, Error 404">Gardenadmin, Error 404</value>
  <value column="Name" original="Page not found">Ñòðàíèöàòà íå áåøå îòêðèòà.</value>
  <value column="ContainerXML" original=""/>
  <value column="StructureXML" original=""/>
  <value column="Title" original=""/>
 </row>
</adempiereTrl>

=== adempiere/adempiere/data/de_DE/CM_Container_Element_Trl_de_DE.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--<!DOCTYPE adempiereTrl PUBLIC "-//ComPiere, Inc.//DTD Adempiere Translation 1.0//EN" "http://www.adempiere.net/dtd/adempiereTrl.dtd">-->
<adempiereTrl language="de_DE" table="CM_Container_Element">
 <row id="100" trl="N">
  <value column="Name" original="content1">content1</value>
  <value column="Description" original=""/>
  <value column="Help" original=""/>
 </row>
 <row id="101" trl="N">
  <value column="Name" original="headline1">headline1</value>
  <value column="Description" original=""/>
  <value column="Help" original=""/>
 </row>
 <row id="102" trl="N">
  <value column="Name" original="content1">content1</value>
  <value column="Description" original=""/>
  <value column="Help" original=""/>
 </row>
 <row id="103" trl="N">
  <value column="Name" original="headline1">headline1</value>
  <value column="Description" original=""/>
  <value column="Help" original=""/>
 </row>
 <row id="104" trl="N">
  <value column="Name" original="content1">content1</value>
  <value column="Description" original=""/>
  <value column="Help" original=""/>
 </row>
 <row id="105" trl="N">
  <value column="Name" original="headline1">headline1</value>
  <value column="Description" original=""/>
  <value column="Help" original=""/>
 </row>
</adempiereTrl>

=== adempiere/adempiere/data/de_DE/PP_Order_BOM_Trl_de_DE.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--<!DOCTYPE adempiereTrl PUBLIC "-//ComPiere, Inc.//DTD Adempiere Translation 1.0//EN" "http://www.adempiere.com/dtd/adempiereTrl.dtd">-->
<adempiereTrl language="de_DE" table="PP_Order_BOM">
 <row id="50000" trl="N">
  <value column="Name" original="Fertilizer #50">Fertilizer #50</value>
  <value column="Description" original="50 # Bag of Lawn Fertilizer">50 # Bag of Lawn Fertilizer</value>
  <value column="Help" original=""/>
 </row>
 <row id="50001" trl="N">
  <value column="Name" original="Fertilizer #70">Fertilizer #70</value>
  <value column="Description" original="70 # Bag of Lawn Fertilizer">70 # Bag of Lawn Fertilizer</value>
  <value column="Help" original=""/>
 </row>
</adempiereTrl>
